# Generated by Django 5.1.3 on 2024-11-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dato',
            old_name='Dato',
            new_name='dato',
        ),
        migrations.RenameField(
            model_name='dato',
            old_name='ID',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='dato',
            name='Fecha',
        ),
        migrations.AddField(
            model_name='dato',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=10),
            preserve_default=False,
        ),
    ]
