# Generated by Django 5.1.3 on 2024-11-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_rename_dato_dato_dato_rename_id_dato_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dato',
            old_name='dato',
            new_name='Dato',
        ),
        migrations.RenameField(
            model_name='dato',
            old_name='fecha',
            new_name='Fecha',
        ),
        migrations.RenameField(
            model_name='dato',
            old_name='id',
            new_name='ID',
        ),
        migrations.AlterModelTable(
            name='dato',
            table='data',
        ),
    ]
